on:
  workflow_dispatch:

jobs:
  left4dead2_dlc2:
    name: "Sync left4dead2_dlc2 folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download left4dead2_dlc2 folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./left4dead2_dlc2 /home/runner/work/left4dead2/left4dead2/left4dead2_dlc2 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            sudo apt install git-lfs
            git lfs install
            git lfs track "*.vpk"
            git add .gitattributes

            git add .
            git commit -m "Add changes in left4dead2_dlc2"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
            atomic: false
