on:
  workflow_dispatch:

jobs:
  steam_cmd:
    name: "Sync steamcmd folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download steamcmd folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./steamcmd /home/runner/work/left4dead2/left4dead2/steamcmd 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in steamcmd"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}



  steam_apps:
    name: "Sync steamapps folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download steamapps folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./steamapps /home/runner/work/left4dead2/left4dead2/steamapps 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in steamapps"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}


  bin:
    name: "Sync bin folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download bin folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./bin /home/runner/work/left4dead2/left4dead2/bin 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in bin"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}


  update:
    name: "Sync update folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download update folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./update /home/runner/work/left4dead2/left4dead2/update 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in update"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}


  platform:
    name: "Sync platform folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download platform folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./platform /home/runner/work/left4dead2/left4dead2/platform 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in platform"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}


  left4dead2:
    name: "Sync left4dead2 folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download left4dead2 folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./left4dead2 /home/runner/work/left4dead2/left4dead2/left4dead2 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in left4dead2"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}


  hl2:
    name: "Sync hl2 folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download hl2 folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./hl2 /home/runner/work/left4dead2/left4dead2/hl2 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in hl2"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}


  left4dead2_lv:
    name: "Sync left4dead2_lv folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download left4dead2_lv folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./left4dead2_lv /home/runner/work/left4dead2/left4dead2/left4dead2_lv 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            sudo apt install git-lfs
            git lfs install
            git lfs track "*.vpk"
            git lfs track "*.bik"
            git add .gitattributes

            git add .
            git commit -m "Add changes in left4dead2_lv"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.WORKFLOW_TOKEN }}
            branch: ${{ github.ref }}

  left4dead2_dlc3:
    name: "Sync left4dead2_dlc3 folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}

        - name: Download left4dead2_dlc3 folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./left4dead2_dlc3 /home/runner/work/left4dead2/left4dead2/left4dead2_dlc3 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in left4dead2_dlc3"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}

  left4dead2_dlc2:
    name: "Sync left4dead2_dlc2 folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download left4dead2_dlc2 folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./left4dead2_dlc2 /home/runner/work/left4dead2/left4dead2/left4dead2_dlc2 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in left4dead2_dlc2"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}

  left4dead2_dlc1:
    name: "Sync left4dead2_dlc1 folder"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            lfs: true
            token: ${{ secrets.WORKFLOW_TOKEN }}
    
        - name: Download left4dead2_dlc1 folder from FTP
          uses: joutvhu/ftp-transfer@v1
          with:
            host: ${{secrets.FTP_HOST}}
            port: 21
            username: ${{secrets.FTP_USERNAME}}
            password: ${{secrets.FTP_PASSWORD}}
            commands: |
              get ./left4dead2_dlc1 /home/runner/work/left4dead2/left4dead2/left4dead2_dlc1 
              
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

            git add .
            git commit -m "Add changes in left4dead2_dlc1"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
